import "./globals.css";
import ConditionalLayout from "./ConditionalLayout";
import { IBM_Plex_Sans } from "next/font/google";

// next/font/google self-hosts as WOFF2 with latin subsetting at build time.
// This replaces the local TTF files (which are ~30-40% larger) and eliminates
// the duplicate font request (with/without ?dpl=) seen in PageSpeed.
const ibmPlexSans = IBM_Plex_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-sans",
  display: "swap",
});

export const metadata = {
  title: "Nolcha",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ibmPlexSans.variable}`}>
      <body className="font-ibm-plex-sans">
        <ConditionalLayout>
          {children}
        </ConditionalLayout>
      </body>
    </html>
  );
}