import Navbar from "@/components/common/Navbar";
import "./globals.css";
import { Plus_Jakarta_Sans } from 'next/font/google'
import Footer from "@/components/common/Footer";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700','800'], // Choose weights you need
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${plusJakartaSans.className}`}>
      <body>
        <div className="bg-[var(--surface-color)]">
        <Navbar/>
        </div>
        {children}
        <div className="bg-[var(--surface-color2)]">
          <Footer/>
        </div>
      </body>
    </html>
  );
}
